# Generated by Django 4.0.6 on 2022-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_T6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailNumber', models.IntegerField(verbose_name='Tail Number')),
                ('callSign', models.CharField(max_length=12, verbose_name='Callsign')),
                ('takeoffTime', models.DateTimeField(verbose_name='Takeoff Time')),
                ('three55', models.CharField(default='none', max_length=100, verbose_name='355 Comments')),
                ('landTime', models.DateTimeField(verbose_name='Final Landing Time')),
                ('solo', models.BooleanField(default=False, verbose_name='Solo')),
                ('formation', models.BooleanField(default=False, verbose_name='Formation')),
                ('crossCountry', models.BooleanField(default=False, verbose_name='X-Country')),
                ('localFlight', models.BooleanField(default=True, verbose_name='LocalFlight')),
                ('inEastsidePattern', models.BooleanField(default=True, verbose_name='Currently in Eastside Pattern')),
                ('emergency', models.BooleanField(default=False, verbose_name='Emergency')),
                ('natureOfEmergency', models.CharField(max_length=200, verbose_name='Nature of Emergency:')),
            ],
        ),
        migrations.CreateModel(
            name='Completed_T6_Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailNumber', models.IntegerField(verbose_name='Tail Number')),
                ('callSign', models.CharField(max_length=12, verbose_name='Callsign')),
                ('takeoffTime', models.DateTimeField(verbose_name='Takeoff Time')),
                ('landTime', models.DateTimeField(verbose_name='Final Landing Time')),
                ('three55', models.CharField(default='none', max_length=100, verbose_name='355 Comments')),
                ('solo', models.BooleanField(default=False, verbose_name='Solo')),
                ('formation', models.BooleanField(default=False, verbose_name='Formation')),
                ('crossCountry', models.BooleanField(default=False, verbose_name='X-Country')),
                ('localFlight', models.BooleanField(default=True, verbose_name='LocalFlight')),
                ('inEastsidePattern', models.BooleanField(default=True, verbose_name='Currently in Eastside Pattern')),
                ('emergency', models.BooleanField(default=False, verbose_name='Emergency')),
                ('natureOfEmergency', models.CharField(max_length=200, verbose_name='Nature of Emergency:')),
            ],
        ),
    ]
