# Generated by Django 4.0.6 on 2022-07-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_t6',
            name='id',
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='callSign',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Callsign'),
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='landTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final Landing Time'),
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='natureOfEmergency',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nature of Emergency:'),
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='tailNumber',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Tail Number'),
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='takeoffTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Takeoff Time'),
        ),
    ]
