# Generated by Django 4.0.6 on 2022-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0002_remove_active_t6_id_alter_active_t6_callsign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_t6',
            name='three55',
        ),
        migrations.AddField(
            model_name='active_t6',
            name='Comments',
            field=models.CharField(default='none', max_length=200, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='three55Code',
            field=models.CharField(default='none', max_length=5, verbose_name='355 Code'),
        ),
    ]
