# Generated by Django 4.0.6 on 2022-07-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0003_remove_active_t6_three55_active_t6_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_t6_sortie',
            name='three55',
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='Comments',
            field=models.CharField(default='none', max_length=200, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='three55Code',
            field=models.CharField(default='none', max_length=5, verbose_name='355 Code'),
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='inEastsidePattern',
            field=models.BooleanField(default=True, verbose_name='Eastside Pattern'),
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='tailNumber',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Tail'),
        ),
        migrations.AlterField(
            model_name='completed_t6_sortie',
            name='callSign',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Callsign'),
        ),
        migrations.AlterField(
            model_name='completed_t6_sortie',
            name='inEastsidePattern',
            field=models.BooleanField(default=True, verbose_name='Eastside Pattern'),
        ),
        migrations.AlterField(
            model_name='completed_t6_sortie',
            name='landTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final Landing Time'),
        ),
        migrations.AlterField(
            model_name='completed_t6_sortie',
            name='natureOfEmergency',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nature of Emergency:'),
        ),
        migrations.AlterField(
            model_name='completed_t6_sortie',
            name='takeoffTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Takeoff Time'),
        ),
    ]
