# Generated by Django 4.0.6 on 2022-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0004_remove_completed_t6_sortie_three55_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=150, null=True, verbose_name='message')),
            ],
        ),
    ]
