# Generated by Django 4.1 on 2022-09-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_t6',
            name='alt_baro',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Altitude'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='alt_geom',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Altitude-Geometric'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='groundSpeed',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Ground Speed'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Lon'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='rssi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='rssi'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='seen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='seen'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='squawk',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Squawk'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='active_t6',
            name='track',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='alt_baro',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Altitude'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='alt_geom',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Altitude-Geometric'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='groundSpeed',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Ground Speed'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Lon'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='rssi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='rssi'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='seen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='seen'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='squawk',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Squawk'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='track',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='active_t6',
            name='tailNumber',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Tail'),
        ),
    ]
