# Generated by Django 4.1 on 2022-09-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0006_active_t6_alt_baro_active_t6_alt_geom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('FAAcode', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='FAA Code')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='active_t6',
            name='aircraftType',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Tails',
            fields=[
                ('tail', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Tail')),
                ('airfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.airfield')),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Name')),
                ('primaryAircraftType', models.CharField(blank=True, max_length=20, null=True, verbose_name='Primary Aircraft Type')),
                ('airfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.airfield')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='lat')),
                ('lon', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='lon')),
                ('alt', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='altitude')),
                ('runway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.runway')),
            ],
        ),
        migrations.CreateModel(
            name='Callsigns',
            fields=[
                ('callsign', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Callsigns')),
                ('aircraftType', models.CharField(blank=True, max_length=20, null=True, verbose_name='Aircraft Type')),
                ('typoe', models.CharField(default='dual', max_length=20, verbose_name='Type')),
                ('homeField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.airfield')),
            ],
        ),
        migrations.AddField(
            model_name='active_t6',
            name='runway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.runway'),
        ),
        migrations.AddField(
            model_name='completed_t6_sortie',
            name='runway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.runway'),
        ),
    ]
