# Generated by Django 4.1 on 2022-09-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0007_airfield_active_t6_aircrafttype_tails_runway_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraftType', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type')),
                ('tailNumber', models.IntegerField(verbose_name='Tail Number')),
                ('callSign', models.CharField(blank=True, max_length=12, null=True, verbose_name='Callsign')),
                ('takeoffTime', models.DateTimeField(blank=True, null=True, verbose_name='Takeoff Time')),
                ('three55Code', models.CharField(default='none', max_length=5, verbose_name='355 Code')),
                ('Comments', models.CharField(default='none', max_length=200, verbose_name='Comments')),
                ('landTime', models.DateTimeField(blank=True, null=True, verbose_name='Final Landing Time')),
                ('solo', models.BooleanField(default=False, verbose_name='Solo')),
                ('formation', models.BooleanField(default=False, verbose_name='Formation')),
                ('crossCountry', models.BooleanField(default=False, verbose_name='X-Country')),
                ('localFlight', models.BooleanField(default=True, verbose_name='LocalFlight')),
                ('inEastsidePattern', models.BooleanField(default=True, verbose_name='Eastside Pattern')),
                ('emergency', models.BooleanField(default=False, verbose_name='Emergency')),
                ('natureOfEmergency', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nature of Emergency:')),
                ('groundSpeed', models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Ground Speed')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Lat')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Lon')),
                ('alt_baro', models.CharField(blank=True, max_length=12, null=True, verbose_name='Altitude')),
                ('alt_geom', models.CharField(blank=True, max_length=12, null=True, verbose_name='Altitude-Geometric')),
                ('track', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Track')),
                ('squawk', models.CharField(blank=True, max_length=10, null=True, verbose_name='Squawk')),
                ('seen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='seen')),
                ('rssi', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='rssi')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='State')),
                ('runway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.runway')),
            ],
        ),
        migrations.RenameModel(
            old_name='Active_T6',
            new_name='ActiveAircraft',
        ),
        migrations.DeleteModel(
            name='Completed_T6_Sortie',
        ),
    ]
