# Generated by Django 4.1 on 2022-09-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0008_completedsortie_rename_active_t6_activeaircraft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeaircraft',
            name='runway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.airfield'),
        ),
        migrations.AlterField(
            model_name='completedsortie',
            name='runway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.airfield'),
        ),
    ]
