# Generated by Django 4.0.6 on 2022-10-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRecorder', '0009_alter_activeaircraft_runway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendAllMessages', models.BooleanField(default=False, verbose_name='Send Message')),
            ],
        ),
        migrations.RenameField(
            model_name='activeaircraft',
            old_name='runway',
            new_name='homeField',
        ),
        migrations.RenameField(
            model_name='callsigns',
            old_name='typoe',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='completedsortie',
            old_name='runway',
            new_name='homeField',
        ),
        migrations.RemoveField(
            model_name='activeaircraft',
            name='crossCountry',
        ),
        migrations.RemoveField(
            model_name='activeaircraft',
            name='inEastsidePattern',
        ),
        migrations.RemoveField(
            model_name='activeaircraft',
            name='localFlight',
        ),
        migrations.RemoveField(
            model_name='completedsortie',
            name='crossCountry',
        ),
        migrations.RemoveField(
            model_name='completedsortie',
            name='inEastsidePattern',
        ),
        migrations.RemoveField(
            model_name='completedsortie',
            name='localFlight',
        ),
        migrations.AddField(
            model_name='activeaircraft',
            name='lastState',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last State'),
        ),
        migrations.AddField(
            model_name='activeaircraft',
            name='substate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Substate'),
        ),
        migrations.AddField(
            model_name='activeaircraft',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='completedsortie',
            name='lastState',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last State'),
        ),
        migrations.AddField(
            model_name='completedsortie',
            name='substate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Substate'),
        ),
        migrations.AddField(
            model_name='completedsortie',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='runway',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.runway'),
        ),
        migrations.AlterField(
            model_name='runway',
            name='airfield',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AutoRecorder.airfield'),
        ),
    ]
