# Generated by Django 4.1 on 2022-09-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='T6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailNumber', models.IntegerField(verbose_name='Tail Number')),
                ('callSign', models.CharField(max_length=12, verbose_name='Callsign')),
                ('takeoffTime', models.DateTimeField(verbose_name='Initial Takeoff Time')),
                ('landTime', models.DateTimeField(verbose_name='Final Landing Time')),
                ('three55', models.CharField(default='none', max_length=100, verbose_name='355 Comments')),
                ('solo', models.BooleanField(default=False, verbose_name='Solo')),
                ('formation', models.BooleanField(default=False, verbose_name='Formation')),
                ('crossCountry', models.BooleanField(default=False, verbose_name='X-Country')),
                ('localFlight', models.BooleanField(default=True, verbose_name='LocalFlight')),
                ('inEastsidePattern', models.BooleanField(default=True, verbose_name='Currently in Eastside Pattern')),
                ('emergency', models.BooleanField(default=False, verbose_name='Emergency')),
                ('natureOfEmergency', models.CharField(max_length=200, verbose_name='Nature of Emergency:')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
