# Generated by Django 4.0.6 on 2022-07-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailNumber', models.IntegerField()),
                ('callSign', models.CharField(max_length=12)),
                ('takeoffTime', models.DateTimeField(verbose_name='Initial Takeoff Time')),
                ('landTime', models.DateTimeField(verbose_name='Final Landing Time')),
                ('three55', models.CharField(default='none', max_length=100)),
                ('solo', models.BooleanField(default=False)),
                ('formation', models.BooleanField(default=False)),
                ('crossCountry', models.BooleanField(default=False)),
                ('localFlight', models.BooleanField(default=True)),
                ('inEastsidePattern', models.BooleanField(default=True)),
                ('emergency', models.BooleanField(default=False)),
                ('natureOfEmergency', models.CharField(max_length=200)),
            ],
        ),
    ]
