<<<<<<< Updated upstream
# Generated by Django 4.0.6 on 2022-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_t6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t6',
            name='callSign',
            field=models.CharField(max_length=12, verbose_name='Callsign'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='crossCountry',
            field=models.BooleanField(default=False, verbose_name='X-Country'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='emergency',
            field=models.BooleanField(default=False, verbose_name='Emergency'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='formation',
            field=models.BooleanField(default=False, verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='inEastsidePattern',
            field=models.BooleanField(default=True, verbose_name='Currently in Eastside Pattern'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='localFlight',
            field=models.BooleanField(default=True, verbose_name='LocalFlight'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='natureOfEmergency',
            field=models.CharField(max_length=200, verbose_name='Nature of Emergency:'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='solo',
            field=models.BooleanField(default=False, verbose_name='Solo'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='tailNumber',
            field=models.IntegerField(verbose_name='Tail Number'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='three55',
            field=models.CharField(default='none', max_length=100, verbose_name='355 Comments'),
        ),
    ]
=======
# Generated by Django 4.0.6 on 2022-07-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_t6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t6',
            name='callSign',
            field=models.CharField(max_length=12, verbose_name='Callsign'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='crossCountry',
            field=models.BooleanField(default=False, verbose_name='X-Country'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='emergency',
            field=models.BooleanField(default=False, verbose_name='Emergency'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='formation',
            field=models.BooleanField(default=False, verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='inEastsidePattern',
            field=models.BooleanField(default=True, verbose_name='Currently in Eastside Pattern'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='localFlight',
            field=models.BooleanField(default=True, verbose_name='LocalFlight'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='natureOfEmergency',
            field=models.CharField(max_length=200, verbose_name='Nature of Emergency:'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='solo',
            field=models.BooleanField(default=False, verbose_name='Solo'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='tailNumber',
            field=models.IntegerField(verbose_name='Tail Number'),
        ),
        migrations.AlterField(
            model_name='t6',
            name='three55',
            field=models.CharField(default='none', max_length=100, verbose_name='355 Comments'),
        ),
    ]
>>>>>>> Stashed changes
